; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = file://external/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D DEBUG_LOGGING_ENABLED
custom_sdkconfig = 
	CONFIG_BT_CTRL_MODEM_SLEEP=y
	CONFIG_RMT_SUPPRESS_DEPRECATE_WARN=y
	CONFIG_RMT_SKIP_LEGACY_CONFLICT_CHECK=y
custom_component_remove = 
	espressif/esp_insights
	espressif/esp_rainmaker
	espressif/rmaker_common
	espressif/esp_diagnostics
lib_deps =
	bblanchon/ArduinoJson@^7.4.1
	symlink://C:\Projects\Arduino\DebugModule
	symlink://C:\Projects\Arduino\BMI160